### ISSUE TITLE
Unable to read import plotting_modules

### ISSUE THREAD

**Issue by Jithinpm** [mdenolle/NoisePy#25] opened 2021-02-18 08:26 UTC
while giving the command import plotting_modules , its seems an error . Actually i want know which is the directory that i want to give with cd

**Comment by chengxinjiang** [comment] 2021-04-07 03:17
apologies for this very late reply. If possible, could you please provide more information regarding the problems you have. I am not able to help with the info you provided right now.

**Comment by Jithinpm** [comment] 2021-04-07 07:59
Thankyou sir for your consideration.

I am not able to install mpi4py=3.0.1.

Hereby attaching the screenshot of the conda prompt.

Thankfully
JITHIN P M

**Comment by chengxinjiang** [comment] 2021-04-08 10:57
I see. So the problem is not caused by potential bugs in the NoisePy, but rather installing the dependent libraries. In this case, I will need to close this issue. The complex environment and system at the users' end make it really hard to provide a useful suggestion. But I would like to suggest you try "pip install mpi4py" to see whether it helps you install the mpi4py.

**Closed by chengxinjiang** 2021-04-08 10:57 UTC

**Comment by Jithinpm** [comment] 2021-04-08 11:07
Sir but in pip i failed to install obspy.
Hereby attaching the screenshot.
